import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  Box,
  Center,
  useColorModeValue,
  Heading,
  Text,
  SimpleGrid,
  Stack,
} from "@chakra-ui/react";
import Cards from "./components/Cards";
import Heros from "./components/Heros";
import Navbar from "./components/Navbar";
import Templates from "./products/Templates";
import Career from "./components/Career";
import Footer from "./components/Footer";
import Contact from "./components/Contact";
import Prizes from "./components/Prizes";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <Heros></Heros>

      <Center>
        <Heading
          fontWeight={600}
          fontSize={{ base: "3xl", sm: "4xl", md: "6xl" }}
          lineHeight={"110%"}
          pt={32}
          pb={16}
        >
          Port{" "}
          <Text as={"span"} color={"orange.400"}>
            folio
          </Text>
        </Heading>
      </Center>
      <Box p={4} pb={32}>
        <Center>
          <SimpleGrid columns={{ base: 1, md: 3 }} spacing={12}>
            <Cards
              title="OTC Swap"
              description="NFTswap tool"
              image="images/otc-swap.png"
            />
            <Cards
              title="ArbX NFT"
              description="Arbitrum Native NFT Bridge"
              image="images/ArbXNFT.png"
            />
            <Cards
              title="DAyOri"
              description="Notification tool for DAO"
              image="images/dayori.png"
            />
            <Cards
              title="ZipChain"
              description="Notification tool for DAO"
              image="images/zipchain.png"
            />
            <Cards
              title="NFT Hashi"
              description="Trsutminimized NFT Cross-chain Bridge"
              image="images/nfthashi.png"
            />
            <Cards
              title="Chocomint"
              description="No-code NFT minting tool"
              image="images/chocomint.jpeg"
            />
            <Cards
              title="DMTP"
              description="Decentralized Message Transfer Protocol"
              image="images/dmtp.jpeg"
            />
            <Cards
              title="Metadata Decentralizer"
              description="Notification tool for DAO"
              image="images/dayori.png"
            />
          </SimpleGrid>
        </Center>
      </Box>
      <Career></Career>
      <Prizes></Prizes>

      <Contact></Contact>
      <Footer></Footer>
    </>
  );
}
